spring: 
  jpa: 
    hibernate: 
      dll-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      
  datasource: 
    url: jdbc:mysql://localhost:3306/poc?useSSL=false
    username: root
    password: root
  
logging: 
  level: 
    org: 
      hibernate: 
        SQL: DEBUG
      type: 
        descriptor: 
          sql: 
            BasicBinder: TRACE
